Document: vulkan-utility-libraries
Title: Debian vulkan-utility-libraries Manual
Author: <insert document author here>
Abstract: This manual describes what vulkan-utility-libraries is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/vulkan-utility-libraries/vulkan-utility-libraries.sgml.gz

Format: postscript
Files: /usr/share/doc/vulkan-utility-libraries/vulkan-utility-libraries.ps.gz

Format: text
Files: /usr/share/doc/vulkan-utility-libraries/vulkan-utility-libraries.text.gz

Format: HTML
Index: /usr/share/doc/vulkan-utility-libraries/html/index.html
Files: /usr/share/doc/vulkan-utility-libraries/html/*.html
